name: TaskTracker Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run security tests
        run: node tests/security/security-checks.js

  unit_test:
    runs-on: ubuntu-latest
    needs: security_test
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: node tests/unit/tasktracker.test.js

  integration_test:
    runs-on: ubuntu-latest
    needs: unit_test
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run integration tests
        run: node tests/integration/claude-integration.test.js

  cost_optimization_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check for batch templates
        run: |
          # Ensure Claude batch templates exist
          if [ ! -d "examples/claude-templates" ]; then
            echo "❌ Claude templates directory missing"
            exit 1
          fi
          
          # Check for required template files
          required_templates=("daily-update.txt" "task-create.txt" "pr-prepare.txt")
          for template in "${required_templates[@]}"; do
            if [ ! -f "examples/claude-templates/$template" ]; then
              echo "❌ Missing template: $template"
              exit 1
            fi
          done
          
          echo "✅ All required templates found" 